### ISSUE TITLE
Advancement text on client side not resolved.

### ISSUE THREAD

**Issue by CiskaLV** [pedruhb/MoreAdvancements#1]
I might have done something wrong as I'm running this mod only on the server, but when you get an advancement or lookt at the tree their names are not the actual String value but the path.
Example:
![image](https://i.ciska.lv/NubE7hw.png)

**Comment by Random-MCreator-Dev** [comment]
What language are you using?

**Comment by ghost** [comment]
Either you aren't using American English as your language, or you just need to install the mod onto your client.
